### ISSUE TITLE
Error with plugin

### ISSUE THREAD

**Issue by creps** [FawadNL/tickera-apple-wallet#2]
Hi!!

I have installed your Apple Wallet Pass plugin Tickera, but after having configured it correctly with all the data related to Apple, after placing the order (after making the payment) the page gene rates a fatal error and does not work, and I see How many followers is the subject of the plugin but I would not know where the problem is.

The php Log gives the following result:
[Wed Oct 08 09: 20: 24.865684 2019] [proxy_fcgi: error] [76410 pid: tid 139846483900160] AH01071: Got error "message PHP: id was called Incorrectly. Order properties Should not be accessed directly. Backtrace: require ( 'wp-blog-header.php'), require_once ( 'wp-includes / template-loader.php), do_action (template_redirect), WP_Hook-> do_action, WP_Hook-> apply_filters, WC_AJAX :: do_wc_ajax, do_action (wc_ajax_checkout), WP_Hook-> do_action, WP_Hook-> apply_filters, WC_AJAX :: checkout, WC_Checkout-> process_checkout, WC_Checkout-> process_order_payment, woocommerce_paytpv-> process_payment, WC_Abstract_Legacy_Order -> __ get, wc_doing_it_wrong. This message was added in version 3.0 \ NPHP message:. Order_key was called Incorrectly. Order properties Should not be accessed directly. Backtrace: require ( 'wp-blog-header.php'), require_once ( 'wp-includes / template-loader.php), do_action (template_redirect), WP_Hook-> do_action, WP_Hook-> apply_filters, WC_AJAX :: do_wc_ajax, do_action (wc_ajax_checkout), WP_Hook-> do_action, WP_Hook-> apply_filters, WC_AJAX :: checkout, WC_Checkout-> process_checkout, WC_Checkout-> process_order_payment, woocommerce_paytpv-> process_payment, WC_Abstract_Legacy_Order -> __ get, wc_doing_it_wrong. This message was added in version 3.0 \ NPHP message:. The woocommerce_get_page_id function is deprecated since version 3.0. Replace with wc_get_page_id \ NPHP message:. Wc_get_page_id The argument is deprecated since version 2.1. The "pay" and "thanks" pages are no-longer used - an endpoint is added to the checkout instead.https://<private-ip>.com/tickets-payment/

[Wed Oct 08 09: 20: 41.049992 2019] [proxy_fcgi: error] [76410 pid: tid 139846517470976]  AH01071: Got error "PHP message: Fatal error PHP: Uncaught Exception Logic: Can not use SplFileObject with directories /var/www/vhosts/<private-ip>/<private-ip>/wp-content/plugins/Tickera-Apple-Wallet-master/vendor/eo/passbook/src/Passbook/Certificate/Certificate.php:26 \ nStack trace: \ n # 0 /var/www/vhosts/<private-ip>/<private-ip>/wp-content/plugins/Tickera-Apple-Wallet-master/vendor/eo/passbook/src/Passbook/Certificate /Certificate.php(26) SplFileObject -> __ construct ( '/ var / www / vhosts ...) \ n # 1 /var/www/vhosts/<private-ip>/<private-ip>/wp-content/ plugins / Tickera-Apple Wallet master / vendor / eo / passbook / src / Passbook / Certificate / P12.php (29) Passbook \\ \\ Certificate Certificate -> __ construct ( '/var/www/vhosts...')\n#2 /var/www/vhosts/<private-ip>/<private-ip>.com/wp-content/plugins/Tickera-Apple-Wallet-master/vendor/eo/ passbook / src / PBS / PassFactory.php (107): passbook Certificate \\ \\ P12 -> __ construct ( '/ var / www / vhosts ...', 'test') \ n # 3 / var / www / vhosts /<private-ip>.es/<private-ip>.com/wp-content/plugins/Tickera-Apple-Wall...\n "referer:https://www.paytpv.com/gateway/stdgw.php

**Comment by FawadNL** [comment]
@creps the first issue is related to some other plugin that is using deprecated woo functions. We don't use those functions. 

The second issue derives from an outdated MySQL DB, please update to latest stable version to resolve the issue.

Closing this ticket for now.
