### ISSUE TITLE
Multiple Tickets and Seating Charts

### ISSUE THREAD

**Issue by pandafour** [FawadNL/tickera-apple-wallet#5]
Hello - I'm running into an issue with ordering multiple tickets. Each "add to Apple wallet" button that appears in the order confirmation email and on the website replaces the currently stored ticket in the wallet. Is there a way to create separate ticket instances in Apple Wallet? Or group multiple tickets together and swipe side to side to view?

I realize it has been a few years since this was updated. Not sure how easy it is to pull seating chart data from the orders too or if this can be added alongside the customer/location info in the ticket display.

**Comment by pandafour** [comment]
I was able to pull the seat assignment from the $seat_label post meta in case anyone needs this. Still not sure how to handle multiple tickets. Each pass file replaces the previous one already in the wallet.

**Comment by TokioTom** [comment]
Can you tell me, how you added the $seat_label value to the wallet-pass? It's not very good tinkering with the files if you don't really know, where to put that additional field. I have it already on my "normal" paper-tickets, but in which of the json or php do I have to add that? Thanks for an answer...

**Comment by pandafour** [comment]
Here is my adjusted code to add seating chart labels and multiple ticket instances (iOS users can add multiple tickets for the same event without overwriting previously added tickets). I removed the first/last name portion on the ticket for my purposes, but if you need it you can add it back from the original author. Replace the "apple_wallet_pass.php" with this code and you should be all set.

https://github.com/pandafour/Tickera-Apple-Wallet/blob/master/apple_wallet_pass.php

**Comment by TokioTom** [comment]
Thank you very much! That helps a lot!!
